#############################################################
#                  Other Chart Collections                  #
#         Created by Yozora, Bullmoose20, & Sohjiro         #
#############################################################
#  Call this from your config.yml (Movie or Show)           #
#  If nothing is specified these are the defaults           #
#                                                           #
#    metadata_path:                                         #
#      - git: PMM/chart/other                               #
#        template_variables:                                #
#          # Sets the collection mode of the collection     #
#          collection_mode:                                 #
#          # Sets the value at the start of the sort title  #
#          collection_section: "01"                         #
#                                                           #
#   # Turn the Sondheim's Favorite Films collection on/off  #
#     use_sondheim_picks: true                              #
#     # Determines collection order in it's section         #
#     order_sondheim_picks:                                 #
#     # Set visible_library for Sondheim's Favorite         #
#     visible_library_sondheim_picks: false                 #
#     # Set visible_home for Sondheim's Favorite            #
#     visible_home_sondheim_picks: false                    #
#     # Set visible_shared for Sondheim's Favorite          #
#     visible_shared_sondheim_picks: false                  #
#############################################################

external_templates:
  repo: PMM/templates
  template_variables:
    collection_section: "01"

collections:
  Sondheim's Favorite Films:
    letterboxd_list_details: https://letterboxd.com/akasharpie321/list/stephen-sondheims-favorite-films/
    file_poster: /config/SondheimsFavoriteFilms.jpg
    show_missing: true
    template:
      - name: customsync
      - name: chart_shared
        key: sondheim-picks
