#############################################################
#                  Other Chart Collections                  #
#         Created by Yozora, Bullmoose20, & Sohjiro         #
#############################################################
#  Call this from your config.yml (Movie or Show)           #
#  If nothing is specified these are the defaults           #
#                                                           #
#    metadata_path:                                         #
#      - git: PMM/chart/other                               #
#        template_variables:                                #
#          # Sets the collection mode of the collection     #
#          collection_mode:                                 #
#          # Sets the value at the start of the sort title  #
#          collection_section: "01"                         #
#                                                           #
#      # Turn the Letterboxd Top 250 collection on/off      #
#      use_letterboxd_250_narrative: true                   #
#      # Determines collection order in it's section        #
#      order_letterboxd_250_narrative:                      #
#      # Set visible_library for Letterboxd Top 250         #
#      visible_library_letterboxd_250_narrative: false      #
#      # Set visible_home for Letterboxd Top 250            #
#      visible_home_letterboxd_250_narrative: false         #
#      # Set visible_shared for Letterboxd Top 250          #
#      visible_shared_letterboxd_250_narrative: false       #
#                                                           #
#    # Turn the Letterboxd Top 250 Docs collection on/off   #
#    use_letterboxd_250_docs: true                          #
#    # Determines collection order in it's section          #
#    order_letterboxd_250_docs:                             #
#    # Set visible_library for Letterboxd Top 250 Docs      #
#    visible_library_letterboxd_250_docs: false             #
#    # Set visible_home for Letterboxd Top 250 Docs         #
#    visible_home_letterboxd_250_docs: false                #
#    # Set visible_shared for Letterboxd Top 250 Docs       #
#    visible_shared_letterboxd_250_docs: false              #
#############################################################

external_templates:
  repo: PMM/templates
  template_variables:
    collection_section: "01"

collections:
  Letterboxd Top 250 Narrative Features:
    letterboxd_list_details: https://letterboxd.com/dave/list/official-top-250-narrative-feature-films/
    file_poster: /config/LetterboxdTop250NarrativeFeatures.jpg
    template:
      - name: customsync
      - name: chart_shared
        key: letterboxd_250_narrative

  Letterboxd Top 250 Docs:
    letterboxd_list_details: https://letterboxd.com/jack/list/official-top-250-documentary-films/
    file_poster: /config/LetterboxdTop250Docs.jpg
    template:
      - name: customsync
      - name: chart_shared
        key: letterboxd_250_docs

